apiVersion: v1
kind: Pod
metadata:
  name: sglang-glm5-benchmark
spec:
  serviceAccountName: sglang-benchmark-ksa
  nodeSelector:
    cloud.google.com/gke-nodepool: g4-384-np-1
  restartPolicy: Never
  volumes:
  - name: workspace-volume
    emptyDir: {}
  containers:
  - name: benchmark
    image: docker.io/lmsysorg/sglang:v0.5.10.post1
    volumeMounts:
    - name: workspace-volume
      mountPath: /workspace
    env:
    - name: HF_TOKEN
      valueFrom:
        secretKeyRef:
          name: hf-secret
          key: HF_TOKEN
    command:
    - /bin/bash
    - -c
    args:
    - |
      echo "Starting SGLang 512-Concurrency Benchmark for GLM-5-NVFP4..."
      
      API_URL="http://sglang-serving-glm51-hf:30000"
      MODEL_NAME="GLM-5.1"
      CONCURRENCY=512
      INPUT_LEN=1024
      OUTPUT_LEN=8192
      NUM_PROMPTS=512

      python3 -m sglang.bench_serving \
          --backend sglang-oai \
          --base-url $API_URL \
          --model $MODEL_NAME \
          --tokenizer lukealonso/GLM-5.1-NVFP4 \
          --dataset-name random \
          --random-input-len $INPUT_LEN \
          --random-output-len $OUTPUT_LEN \
          --num-prompts $NUM_PROMPTS \
          --max-concurrency $CONCURRENCY \
          --output-file /workspace/results_glm5.json \
          --apply-chat-template

      
      echo "Sleeping so you can extract the results manually if needed..."
      sleep infinity

